# graph.py

from typing import TypedDict, List
from langgraph.graph import StateGraph, END
from langchain_core.messages import BaseMessage, HumanMessage
from langchain_core.tools import Tool
from langchain_google_genai import ChatGoogleGenerativeAI
from tools import search_resumes, calculate_match_score

llm = ChatGoogleGenerativeAI(
    model="gemini-3-flash-preview",
    temperature=0
)

# ✅ DEFINE TOOLS LIST HERE
tools = [
    search_resumes,
    calculate_match_score
]

llm_with_tools = llm.bind_tools(tools)

# -------------------------------------------------
# Graph State Definition
# -------------------------------------------------

class AgentState(TypedDict):
    messages: List[BaseMessage]


# -------------------------------------------------
# Agent Node (Reasoning Step)
# -------------------------------------------------

def agent_node(state: AgentState):
    """
    Calls the LLM to decide the next step.
    The LLM may either:
    - Call a tool
    - Produce a final answer
    """
    response = llm_with_tools.invoke(state["messages"])
    return {"messages": state["messages"] + [response]}


# -------------------------------------------------
# Tool Node (Action Step)
# -------------------------------------------------

def tool_node(state: AgentState):
    """
    Executes tool calls generated by the LLM
    and appends tool results back to the state.
    """
    last_message = state["messages"][-1]

    tool_outputs = []

    for tool_call in last_message.tool_calls:
        tool_map = {
            "search_resumes": search_resumes,
            "calculate_match_score": calculate_match_score
        }

        selected_tool = tool_map[tool_call["name"]]
        output = selected_tool.invoke(tool_call["args"])

        tool_outputs.append(
            HumanMessage(
                content=f"Tool Output ({tool_call['name']}): {output}"
            )
        )

    return {"messages": state["messages"] + tool_outputs}


# -------------------------------------------------
# Conditional Router
# -------------------------------------------------

def router(state: AgentState):
    """
    Determines whether to continue reasoning or stop.
    """
    last_message = state["messages"][-1]

    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tool_node"

    return END


# -------------------------------------------------
# Graph Construction
# -------------------------------------------------

graph = StateGraph(AgentState)

graph.add_node("agent", agent_node)
graph.add_node("tool_node", tool_node)

graph.set_entry_point("agent")

graph.add_conditional_edges(
    "agent",
    router,
    {
        "tool_node": "tool_node",
        END: END
    }
)

graph.add_edge("tool_node", "agent")

app = graph.compile()
